services:
  - type: web
    name: skymessage-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 backend.app:app --bind 0.0.0.0:$PORT
